environment:
  matrix:
    - PYTHON: 'C:\Python36'

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - 'python -m pip install -U pip'
  - 'pip install pyinstaller'
  - 'pip install .'

build_script:
  - 'pyinstaller -F codeplug.py'

test: off

artifacts:
  - path: 'dist\*'
